### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by donnelmandimika** [Slemanof/restaurant_recommender_2001#15]
Double checking the data and user protection alongside traffic within the website

**Comment by Slemanof** [comment]
## Encryption checklist:

- [x] Apply SSL. Issue #113 
- [x] Encrypt/Secret API's keys. #129
- [ ] ~~Encrypt data on the server? Maybe?~~ No need to encrypt data on server for now as SSL is being used to securely communicate with the server.
- [ ] ~~Encrypt/Secret MySQL Credentials.~~ This issue was included in issue #129
