### ISSUE TITLE
Login via Google Authentication

### ISSUE THREAD

**Issue by Slemanof** [Slemanof/restaurant_recommender_2001#20]
We should have a Flask version for user registration/sign-in. However, we would like to allow the users to sign in also via Google Auth for security reasons.

Goal of the ticket is to investigate the back-end construction of such sign-in and create a code that could be integrated if necessary into our site.

**Todo**:
- [x] Basic html file with google authentication.
- [x] Code that allows to run the google authentication and shows a "You are signed in" page.
- [x] Possible other experiments (e.g. it would be interesting to see what information about the user is available to us and how can we access it via Google API).

**Comment by DeC0rtez** [comment]
Prototype code with instructions for usage added to [ref-google-authentication](https://github.com/Slemanof/easyeats.live/tree/ref-google-authentication) branch.  Issue closed and assigned to wontfix as development is no longer ongoing.
