### ISSUE TITLE
Python Pytest

### ISSUE THREAD

**Issue by Stanley008** [Slemanof/restaurant_recommender_2001#29]
Hi,
this thread is going to be about Python Pytest. Any related issue, or gathered information please provide here.

Known issues installation: Be sure that You switch your python version to version 3 and later, as version 2 is not supported any more. Only after that You can install pytest properly. (Install with homebrew or conda or any other sw installator.)

The latest version of Python is 3.8.2

**Comment by Stanley008** [comment]
Here are suggestions for testing:

Restaurant = No more than 50 characters.

Location = up to 9 numbers + 9 numbers

Address = No more than 40 characters.

Rating = No more than 2 digits. No more than 3 characters. (example: 3.6)

Cuisines = No more than 20 characters.

Featured Image = ? test for jpg ?

Highlights = No more than 50 characters.

Phone Number = + 12 numbers or 14 numbers. Delete space and check for +12numbers or only 14 numbers. 

PS: These are not final limitations, they can be adjusted accordingly to other team needs.

**Comment by svarnypetr** [comment]
This is more about input validation/sanitization.

**Comment by Slemanof** [comment]
@svarnypetr hey just to clarify your latest comment 

> this is more about input 

Did you mean @Stanley008 comment?

Suggested tests:

- [x] Testing Zomato's API requests and responses. #55 @Slemanof 

- [x] Testing SQL DB connection. #54 @riccardosl 

- [x] Testing menu updating functionality. #56

- [x] Testing recommender's responses. #57

- [x] Testing address to coordinates functionality. #58 @Stanley

- [ ] Testing Data filtering for Zomato's data. #59

- [ ] Testing OWASP top 10. #60

P.s: [This link](https://github.com/Th3R3p0/AutoSec4WebApps/tree/master/tests) contains some examples of PyTests to have and idea

**Comment by svarnypetr** [comment]
@Slemanof Yes, the one mentioned by Stan is more input validation. I would suggest making this separate issues for all these tests. They are plenty of work by themselves.
