### ISSUE TITLE
Remove public api key refernces

### ISSUE THREAD

**Issue by svarnypetr** [Slemanof/restaurant_recommender_2001#33]
API keys are currently publicly visible which is a security risk.

**Todo**
Replace any occurrence of API keys in the code with a file import that would contain the key and make sure all team members have still access to the API.
- [x] Find all occurrences of API keys in all current branches
- [x] **Add file to .gitignore so that it is not shared**
- [x] Replace with references to file(s)
- [x] Generate **new** keys for API services
- [x] Distribute keys to the team

**Check everyone has working key**
 - [x] Ilyas
 - [x] Riccardo
 - [x] Suli
 - [x] Iryna
 - [x] Don
 - [x] Daniel
 - [x] Jan (?)
 - [x] Stan

**Comment by svarnypetr** [comment]
@Stanley008 @donnelmandimika @DeC0rtez  Do you have working keys? So that this can be closed.
