### ISSUE TITLE
Flask Login infrastructure

### ISSUE THREAD

**Issue by svarnypetr** [Slemanof/restaurant_recommender_2001#95]
We have currently no user login capacity.

The user should be able to register and later on login. The data about the user are stored in the user database.

**Todo**:
- [x] Allow the user to login (i.e. check the database about the user login data and use them to authenticate the user.)
- [x] Allow the user to register (i.e. add new authentication data to the user database).
- [x] Track/keep the user logged in after login operation.
- [x] Add relevant buttons/UI features for login/register/logout.
- [x] Investigate/treat login behaviour in the case the user closes the window/tab/ends the session.
